version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    volumes:
      - /app/node_modules
      - nuxt_composition_sync:/app/:nocopy

volumes:
  nuxt_composition_sync:
    external: true
